### ISSUE TITLE
CMake Fails to Honor GCC 9.3.0 Module Load and Encounters Compilation Errors

### ISSUE THREAD

**Issue by lucaspatel** [maxrossi91/pfp-thresholds#1]
## Description
I am attempting to install pfp-thresholds on our lab compute cluster. I am experiencing issues with CMake not honoring the module load for GCC 9.3.0, leading to problems with identifying the `zlib.h` path.

## Details
- **GCC Version Incompatibility**: The build is not compatible with the default GCC version on our cluster (4.8.5). Even after loading and setting environment variables to force GCC 9.3.0, the build fails.
- **KSEQ Library Bug**: It seems like there is a bug in the KSEQ library. Fixing the cast issue in the library and rebuilding does not resolve the compilation failure.
- **SDSL Compilation Error**: The code fails during compilation at approximately 90%, specifically when handling SDSL. The root cause of this error is unclear.

## Steps to Reproduce
1. Attempt to build the project with the default GCC version (4.8.5).
2. Load and set environment variables to use GCC 9.3.0.
3. Observe the build process and note the points of failure.

## Expected Behavior
The build process should successfully compile with GCC 9.3.0, and all library dependencies should be resolved without errors.

## Actual Behavior
The build process fails despite forcing the use of GCC 9.3.0. Issues are observed with KSEQ library and during SDSL compilation.

## Environment
- **Operating System**: CentOS Linux 7 (Core)
- **CMake Version**: 3.18.2
- **GCC Versions**: 9.3.0

## Additional Context
I also encountered some header issues with zlib when attempting these steps without expiring the `CC` and `CXX` environment variables, despite the fact that zlib is installed on our system in a default location. Some debug information on the steps we've taken is attached below.

```
(base) 16:04:02 (dtmcdonald@barnacle2):pfp-thresholds@master$ module load gcc_9.3.0
(base) 16:04:11 (dtmcdonald@barnacle2):pfp-thresholds@master$ module load cmake_3.18.2
(base) 16:08:32 (dtmcdonald@barnacle2):pfp-thresholds@master$ export CC=$(which gcc)
(base) 16:08:41 (dtmcdonald@barnacle2):pfp-thresholds@master$ export CXX=$(which g++)
(base) 16:08:46 (dtmcdonald@barnacle2):pfp-thresholds@master$ mkdir build; cd build;
(base) 16:08:49 (dtmcdonald@barnacle2):build@master$ cmake ..
-- Setting build type to 'Release' as none was specified.
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
...blah blah...
(base) 16:10:46 (dtmcdonald@barnacle2):build@master$ make
Scanning dependencies of target gsacak64
[  3%] Building C object thirdparty/CMakeFiles/gsacak64.dir/__/_deps/gsacak-src/gsacak.c.o
[  3%] Built target gsacak64
Scanning dependencies of target malloc_count
[  6%] Building C object thirdparty/CMakeFiles/malloc_count.dir/__/_deps/malloc_count-src/malloc_count.c.o
[  6%] Built target malloc_count
...blah blah...
/home/mcdonadt/pfp-thresholds/build/_deps/klib-src/kseq.h:114:32: error: invalid conversion from ‘void*’ to ‘unsigned char*’ [-fpermissive]
  114 |     unsigned char *sep = memchr(ks->buf + ks->begin, delimiter, ks->end - ks->begin); \
      |                          ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                |
      |                                void*
/home/mcdonadt/pfp-thresholds/build/_deps/klib-src/kseq.h:152:2: note: in expansion of macro ‘__KS_GETUNTIL’
  152 |  __KS_GETUNTIL(__read, __bufsize)
      |  ^~~~~~~~~~~~~
/home/mcdonadt/pfp-thresholds/build/_deps/klib-src/kseq.h:228:2: note: in expansion of macro ‘KSTREAM_INIT’
  228 |  KSTREAM_INIT(type_t, __read, 16384)   \
      |  ^~~~~~~~~~~~
/home/mcdonadt/pfp-thresholds/build/_deps/klib-src/kseq.h:233:35: note: in expansion of macro ‘KSEQ_INIT2’
  233 | #define KSEQ_INIT(type_t, __read) KSEQ_INIT2(static, type_t, __read)
      |                                   ^~~~~~~~~~
/home/mcdonadt/pfp-thresholds/build/_deps/r-index-src/internal/r_index.hpp:22:1: note: in expansion of macro ‘KSEQ_INIT’
   22 | KSEQ_INIT(gzFile, gzread);
      | ^~~~~~~~~
make[2]: *** [_deps/r-index-build/CMakeFiles/ri-buildfasta.dir/ri-buildfasta.cpp.o] Error 1
make[1]: *** [_deps/r-index-build/CMakeFiles/ri-buildfasta.dir/all] Error 2
make: *** [all] Error 2

If you fix the cast, then clean, then rebuild, you get:

...blah blah...
/home/mcdonadt/pfp-thresholds/include/pfp/pfp_lcp.hpp:230:58:   required from here
/home/mcdonadt/pfp-thresholds/build/_deps/sdsl-src/include/sdsl/bp_support_sada.hpp:326:45: warning: conversion to ‘long unsigned int’ from ‘sdsl::bp_support_sada<256, 32, sdsl::rank_support_v5<> >::difference_type’ {aka ‘long int’} may change the sign of the result [-Wsign-conversion]
  326 |                 difference_type max_ex    = ex + (m_sml_block_min_max[2*sml_block_idx+1] - 1);
      |                                             ^~
/home/mcdonadt/pfp-thresholds/build/_deps/sdsl-src/include/sdsl/bp_support_sada.hpp:326:48: warning: conversion to ‘sdsl::bp_support_sada<256, 32, sdsl::rank_support_v5<> >::difference_type’ {aka ‘long int’} from ‘long unsigned int’ may change the sign of the result [-Wsign-conversion]
  326 |                 difference_type max_ex    = ex + (m_sml_block_min_max[2*sml_block_idx+1] - 1);
      |                                             ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mcdonadt/pfp-thresholds/build/_deps/sdsl-src/include/sdsl/bp_support_sada.hpp:335:25: warning: unsigned conversion from ‘int’ to ‘sdsl::bp_support_sada<256, 32, sdsl::rank_support_v5<> >::size_type’ {aka ‘long unsigned int’} changes value from ‘-1’ to ‘18446744073709551615’ [-Wsign-conversion]
  335 |                 return -1;
      |                         ^
In file included from /home/mcdonadt/pfp-thresholds/test/src/pfp_lcp.cpp:28:
/home/mcdonadt/pfp-thresholds/include/common/common.hpp: In function ‘void parseArgs(int, char* const*, Args&)’:
/home/mcdonadt/pfp-thresholds/include/common/common.hpp:131:27: warning: this statement may fall through [-Wimplicit-fallthrough=]
  131 |     _internal_messageError( __FILE__, __LINE__, _internal_message(args) )
      |     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mcdonadt/pfp-thresholds/include/common/common.hpp:384:7: note: in expansion of macro ‘error’
  384 |       error(usage);
      |       ^~~~~
/home/mcdonadt/pfp-thresholds/include/common/common.hpp:385:5: note: here
  385 |     case '?':
      |     ^~~~
make[2]: *** [test/src/CMakeFiles/pfp_lcp64.dir/pfp_lcp.cpp.o] Error 1
make[1]: *** [test/src/CMakeFiles/pfp_lcp64.dir/all] Error 2
make: *** [all] Error 2
```

@wasade is helping with this effort. Any assistance is appreciated. Thank you.

**Comment by koeppl** [comment]
It seems to me that the error message after fixing the error is not complete. I only see warnings in your log.
Can you pinpoint where the remaining error could be?

**Comment by maxrossi91** [comment]
Hi, @lucaspatel,

I was able to reproduce the issue and I fixed it in the above PR. Could you please try again, deleting the old build folder and re-running `cmake` so it pulls the correct versions of the repos?

Thanks @koeppl, I think the remaining part of the error was an issue with the re-definition of `max` in `gsakak` that was fixed, causing pfp-threshold to fail the compilation.

Bests,

Max

**Comment by wasade** [comment]
Hi @maxrossi91, thank you so much for the rapid response! It looks like this resolved the issues:

```bash
(qiime2-2023.5) 08:22:28 (dtmcdonald@barnacle2):pfp-thresholds@master$ rm -fr build/
(qiime2-2023.5) 08:22:30 (dtmcdonald@barnacle2):pfp-thresholds@master$ git pull origin master
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 14 (delta 9), reused 12 (delta 9), pack-reused 0
Unpacking objects: 100% (14/14), done.
From https://github.com/maxrossi91/pfp-thresholds
 * branch            master     -> FETCH_HEAD
Updating 6fe11db..0716791
Fast-forward
 include/pfp/dictionary.hpp | 4 ++--
 include/pfp/parse.hpp      | 4 ++--
 2 files changed, 4 insertions(+), 4 deletions(-)
(qiime2-2023.5) 08:22:35 (dtmcdonald@barnacle2):pfp-thresholds@master$ module load gcc_9.3.0
(qiime2-2023.5) 08:22:39 (dtmcdonald@barnacle2):pfp-thresholds@master$ module load cmake_3.18.2
(qiime2-2023.5) 08:22:40 (dtmcdonald@barnacle2):pfp-thresholds@master$ export CC=$(which gcc)
(qiime2-2023.5) 08:22:43 (dtmcdonald@barnacle2):pfp-thresholds@master$ export CXX=$(which g++)
(qiime2-2023.5) 08:22:46 (dtmcdonald@barnacle2):pfp-thresholds@master$ mkdir build; cd build;
(qiime2-2023.5) 08:22:50 (dtmcdonald@barnacle2):build@master$ cmake .. &> cmake.log
(qiime2-2023.5) 08:24:44 (dtmcdonald@barnacle2):build@master$ make &> make.log
(qiime2-2023.5) 08:36:56 (dtmcdonald@barnacle2):build@master$ tail cmake.log
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

Building in Release mode
Building in Release mode
sdsl-lite not found, building as external content
Building in Release mode
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mcdonadt/pfp-thresholds/build
(qiime2-2023.5) 08:41:24 (dtmcdonald@barnacle2):build@master$ tail make.log
      |          ^~~~
In file included from /home/mcdonadt/pfp-thresholds/utils/fasta2plain.cpp:28:
/home/mcdonadt/pfp-thresholds/include/common/common.hpp:328:8: warning: inlining failed in call to ‘Args::~Args() noexcept’: call is unlikely and code size would grow [-Winline]
  328 | struct Args
      |        ^~~~
/home/mcdonadt/pfp-thresholds/utils/fasta2plain.cpp:35:10: note: called from here
   35 |     Args args;
      |          ^~~~
[100%] Linking CXX executable fasta2plain
[100%] Built target fasta2plain
(qiime2-2023.5) 08:41:27 (dtmcdonald@barnacle2):build@master$ ls -lrt
total 1.5M
-rw-r--r--  1 dtmcdonald knightlab  13K Nov 17 08:23 CMakeDoxyfile.in
-rw-r--r--  1 dtmcdonald knightlab  16K Nov 17 08:23 CMakeDoxygenDefaults.cmake
-rw-r--r--  1 dtmcdonald knightlab 3.3K Nov 17 08:23 CPackConfig.cmake
-rw-r--r--  1 dtmcdonald knightlab 3.5K Nov 17 08:23 CPackSourceConfig.cmake
drwxr-xr-x 32 dtmcdonald knightlab   32 Nov 17 08:24 _deps
-rwxr-xr-x  1 dtmcdonald knightlab  13K Nov 17 08:24 pfp_thresholds
-rwxr-xr-x  1 dtmcdonald knightlab  12K Nov 17 08:24 bwt_lcp_thresholds
-rwxr-xr-x  1 dtmcdonald knightlab 9.0K Nov 17 08:24 pfp_lcp
-rwxr-xr-x  1 dtmcdonald knightlab  12K Nov 17 08:24 bwt_lcp
-rw-r--r--  1 dtmcdonald knightlab  31K Nov 17 08:24 CMakeCache.txt
-rw-r--r--  1 dtmcdonald knightlab 176K Nov 17 08:24 Makefile
-rw-r--r--  1 dtmcdonald knightlab 2.1K Nov 17 08:24 cmake_install.cmake
drwxr-xr-x  3 dtmcdonald knightlab    5 Nov 17 08:24 thirdparty
drwxr-xr-x  5 dtmcdonald knightlab    7 Nov 17 08:24 include
drwxr-xr-x  4 dtmcdonald knightlab    6 Nov 17 08:24 test
-rw-r--r--  1 dtmcdonald knightlab 8.0K Nov 17 08:24 cmake.log
drwxr-xr-x  3 dtmcdonald knightlab    6 Nov 17 08:36 utils
-rw-r--r--  1 dtmcdonald knightlab 6.9M Nov 17 08:36 make.log
drwxr-xr-x  5 dtmcdonald knightlab   14 Nov 17 08:36 CMakeFiles
(qiime2-2023.5) 08:41:36 (dtmcdonald@barnacle2):build@master$ ./pfp_thresholds --help
usage: pfp_thresholds [-h] [-w WSIZE] [-p MOD] [-t T] [-s] [-e] [-k] [-v] [-f] [-m] [--parsing] [--compress] input

Tool to build the BWT and the Thresholds for higly repetive files using the approach
described in

   "Constructing thresholds directly from prefix-free parsing"
   by Christina Boucher, Travis Gagie, and Massimiliano Rossi

The input file cannot contain the characters 0, 1 or 2 which are
used internally by the algorithm.

positional arguments:
  input                 input file name

optional arguments:
  -h, --help            show this help message and exit
  -w WSIZE, --wsize WSIZE
                        sliding window size (def. 10)
  -p MOD, --mod MOD     hash modulus (def. 100)
  -t T                  number of helper threads (def. None)
  -s                    compute the start run-length sampled Suffix Array
  -e                    compute the end run-length sampled Suffix Array
  -k                    keep temporary files
  -v                    verbose
  -f                    read fasta
  -m                    print memory usage
  --parsing             stop after the parsing phase (debug only)
  --compress            compress output of the parsing phase (debug only)
```

**Comment by maxrossi91** [comment]
Great! Closing.

**Comment by lucaspatel** [comment]
Thanks so much, @maxrossi91!
